<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { apiRequest } from '@/stores/productStore'

const route = useRoute(); const router = useRouter()
const item = ref(null); const niches = ref([]); const productTypes = ref([]); const models = ref([]); const loading = ref(true); const saving = ref(false); const error = ref(''); const notice = ref(''); const mediaURL = ref(''); const aiModel = ref('');
const draft = ref({})
const dateValue = computed({ get: () => draft.value.published_at ? new Date(draft.value.published_at).toISOString().slice(0,16) : '', set: v => { draft.value.published_at = v ? new Date(v).toISOString() : null } })
const stats = computed(() => item.value?.latest_stats || {})
function copyDraft(i) { return { platform:i.platform||'x', content_format:i.content_format||'post', external_post_id:i.external_post_id||'', canonical_url:i.canonical_url||'', author_handle:i.author_handle||'', original_text:i.original_text||'', media:[...(i.media||[])], source_query:i.source_query||'', published_at:i.published_at||null, status:i.status||'discovered', niche_ids:(i.niches||[]).map(n=>n.id), product_type_ids:(i.product_types||[]).map(n=>n.id), stats: i.latest_stats ? {...i.latest_stats} : null } }
async function load() { loading.value=true; error.value=''; try { const [data, ns, types, ms] = await Promise.all([apiRequest(`/api/content-items/${route.params.id}`), apiRequest('/api/content-niches'), apiRequest('/api/niches').catch(()=>[]), apiRequest('/api/ai/models').catch(()=>[])]); item.value=data; draft.value=copyDraft(data); niches.value=ns||[]; productTypes.value=types||[]; models.value=ms||[]; const saved=localStorage.getItem('ai_model')||''; aiModel.value=saved || models.value[0]?.id||models.value[0]?.model||'' } catch(e){error.value=e.message} finally{loading.value=false} }
async function save() { saving.value=true; error.value=''; notice.value=''; try { item.value=await apiRequest(`/api/content-items/${route.params.id}`,{method:'PATCH',body:JSON.stringify(draft.value)}); draft.value=copyDraft(item.value); notice.value='Perubahan konten disimpan.' } catch(e){error.value=e.message} finally{saving.value=false} }
function addMedia(){const u=mediaURL.value.trim();if(u&&!draft.value.media.includes(u)){draft.value.media.push(u);mediaURL.value=''}}
async function addVariant(){try{const v=await apiRequest(`/api/content-items/${route.params.id}/variants`,{method:'POST',body:JSON.stringify({name:`Varian ${item.value.variants.length+1}`,text:'',source:'manual',model:''})});item.value.variants.push(v)}catch(e){error.value=e.message}}
async function saveVariant(v){try{const out=await apiRequest(`/api/content-variants/${v.id}`,{method:'PATCH',body:JSON.stringify(v)});Object.assign(v,out);notice.value='Varian disimpan.'}catch(e){error.value=e.message}}
async function reformat(){saving.value=true;error.value='';try{const v=await apiRequest(`/api/content-items/${route.params.id}/variants/reformat`,{method:'POST',body:JSON.stringify({model:aiModel.value || localStorage.getItem('ai_model') || '',name:`AI ${new Date().toLocaleString('id-ID')}`})});item.value.variants=[...(item.value.variants||[]),v];notice.value='Varian AI ditambahkan.'}catch(e){error.value=e.message}finally{saving.value=false}}
async function removeVariant(v){if(!confirm('Hapus varian ini?'))return;try{await apiRequest(`/api/content-variants/${v.id}`,{method:'DELETE'});item.value.variants=item.value.variants.filter(x=>x.id!==v.id)}catch(e){error.value=e.message}}
function formatCount(n){if(n===undefined||n===null)return '—';return new Intl.NumberFormat('id-ID',{notation:'compact',maximumFractionDigits:1}).format(n)}
onMounted(load)
</script>

<template>
  <div v-if="loading" class="state">Memuat detail konten...</div>
  <div v-else-if="item" class="detail-page">
    <div class="topbar"><button class="button-secondary" @click="router.push('/content-bank')">← Bank konten</button><span class="top-tags"><span class="status-pill">{{ item.status }}</span><span class="format-pill">{{ item.content_format === 'thread' ? 'Thread' : 'Post biasa' }}</span></span></div>
    <section class="hero"><div><p class="eyebrow">BANK KONTEN / {{ item.platform.toUpperCase() }}</p><h1>Detail konten</h1><p class="muted">Raw konten adalah sumber asli. Semua hasil AI dan edit manual disimpan sebagai varian terpisah.</p></div><a class="button-secondary" :href="item.canonical_url" target="_blank" rel="noreferrer">Buka sumber ↗</a></section>
    <p v-if="error" class="error-box">{{ error }}</p><p v-if="notice" class="save-notice">✓ {{ notice }}</p>
    <div class="layout"><main class="main-col">
      <section class="panel"><div class="section-head"><div><h2>Raw konten</h2><p class="muted">Edit manual konten asli di sini, lalu simpan sebelum membuat varian.</p></div><button class="button-primary" :disabled="saving" @click="save">{{ saving ? 'Menyimpan...' : 'Update raw' }}</button></div><textarea v-model="draft.original_text" class="textarea" rows="10"></textarea></section>
      <section class="panel"><div class="section-head"><div><h2>Varian konten</h2><p class="muted">Tambah sebanyak yang dibutuhkan. Bisa AI, copas, atau tulis manual.</p></div><button class="button-secondary" type="button" @click="addVariant">+ Tambah varian</button></div><div v-if="!item.variants?.length" class="empty">Belum ada varian.</div><article v-for="v in item.variants" :key="v.id" class="variant"><div class="variant-head"><input v-model="v.name" class="input" placeholder="Nama varian"/><span class="muted">{{ v.source || 'manual' }}<span v-if="v.model"> · {{ v.model }}</span></span></div><textarea v-model="v.text" class="textarea" rows="8" placeholder="Copas atau tulis varian konten..."></textarea><div class="actions"><button class="button-primary" :disabled="saving" @click="saveVariant(v)">Simpan varian</button><button class="button-secondary" :disabled="saving" @click="reformat">Reformat AI → varian baru</button><button class="button-danger" @click="removeVariant(v)">Hapus</button></div></article><div class="ai-row"><select v-model="aiModel" class="select"><option value="">Model default</option><option v-for="m in models" :key="m.id || m.model" :value="m.id || m.model">{{ m.label || m.name || m.id || m.model }}</option></select><button class="button-primary" :disabled="saving" @click="reformat">{{ saving ? 'Memproses AI...' : 'Reformat AI jadi varian' }}</button></div></section>
    </main><aside class="side-col">
      <section class="panel"><h2>Metadata</h2><label>Platform<select v-model="draft.platform" class="select"><option value="x">X</option><option value="threads">Threads</option><option value="facebook">Facebook</option></select></label><label>URL sumber<input v-model="draft.canonical_url" class="input"/></label><label>Author<input v-model="draft.author_handle" class="input"/></label><label>Query riset<input v-model="draft.source_query" class="input"/></label><label>Waktu publikasi<input v-model="dateValue" type="datetime-local" class="input"/></label><label>Status<select v-model="draft.status" class="select"><option value="discovered">Discovered</option><option value="curated">Curated</option><option value="archived">Archived</option></select></label><div class="label-block"><strong>Niche konten</strong><label v-for="n in niches" :key="n.id" class="check"><input v-model="draft.niche_ids" type="checkbox" :value="n.id"> {{ n.name }}</label></div><div class="label-block"><strong>Jenis barang</strong><label v-for="n in productTypes" :key="n.id" class="check"><input v-model="draft.product_type_ids" type="checkbox" :value="n.id"> {{ n.name }}</label></div><button class="button-primary full" :disabled="saving" @click="save">{{ saving ? 'Menyimpan...' : 'Simpan metadata & raw' }}</button></section>
      <section class="panel"><h2>Popularitas terakhir</h2><div class="metrics"><div><b>{{ formatCount(stats.like_count) }}</b><small>Likes</small></div><div><b>{{ formatCount(stats.repost_count) }}</b><small>Repost</small></div><div><b>{{ formatCount(stats.reply_count) }}</b><small>Reply</small></div><div><b>{{ formatCount(stats.view_count) }}</b><small>Views</small></div></div><p class="muted">Ditangkap {{ item.published_at ? new Date(item.published_at).toLocaleString('id-ID') : 'tanpa tanggal' }}</p></section>
      <section class="panel"><h2>Media</h2><div class="media-grid"><figure v-for="(src,i) in draft.media" :key="src"><video v-if="/\.(mp4|webm|mov)(\?|$)/i.test(src)" :src="src" controls></video><img v-else :src="src" alt="Media konten"><button class="remove" @click="draft.media.splice(i,1)">×</button></figure></div><div class="add-media"><input v-model="mediaURL" class="input" placeholder="URL gambar/video"><button class="button-secondary" @click="addMedia">Tambah</button></div></section>
    </aside></div>
  </div><p v-else class="state">{{ error || 'Konten tidak ditemukan.' }}</p>
</template>

<style scoped>
.detail-page{display:grid;gap:18px}.topbar,.hero,.section-head,.variant-head,.actions,.ai-row,.add-media{display:flex;align-items:center;justify-content:space-between;gap:10px}.hero h1{font-size:48px;margin:4px 0}.eyebrow{font:12px 'DM Mono';letter-spacing:2px;color:#78867c}.layout{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(280px,.8fr);gap:18px;align-items:start}.main-col,.side-col,.panel,.variant{display:grid;gap:18px;min-width:0}.panel{gap:12px}.side-col{position:sticky;top:18px}.textarea{width:100%;min-height:220px;max-height:520px;box-sizing:border-box;resize:vertical;border:1px solid #cedbd0;border-radius:8px;padding:12px;background:#fffdf9;font:14px 'DM Mono';line-height:1.55}.input,.select{width:100%;box-sizing:border-box}.panel label{display:grid;gap:6px;color:#52655a}.variant{gap:10px;border-top:1px solid #d9e2d8;padding-top:14px}.variant-head .input{max-width:260px}.button-danger,.remove{border:1px solid #e7bdb5;background:#fff5f2;color:#a84f43;border-radius:8px;padding:10px 14px;cursor:pointer}.button-primary:disabled{opacity:.6}.status-pill{font:12px 'DM Mono';color:#1f6b4f;background:#e7f1e8;border-radius:999px;padding:7px 10px}.label-block{display:grid;gap:8px}.check{display:block!important}.check input{accent-color:#1f6b4f}.full{width:100%}.metrics{display:grid;grid-template-columns:1fr 1fr;gap:8px}.metrics div{background:#eef5ed;border-radius:8px;padding:12px}.metrics b,.metrics small{display:block}.metrics b{font-size:23px}.metrics small{color:#78867c;margin-top:4px}.media-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.media-grid figure{position:relative;margin:0;border:1px solid #d9e2d8;border-radius:8px;overflow:hidden}.media-grid img,.media-grid video{display:block;width:100%;height:120px;object-fit:cover}.remove{position:absolute;right:5px;top:5px;border-radius:50%;padding:2px 8px;font-size:18px}.state,.empty{text-align:center;padding:40px;color:#78867c}.error-box{padding:12px;background:#fff0ed;color:#a84f43}.save-notice{color:#176b4f;font-weight:600}@media(max-width:800px){.layout{grid-template-columns:1fr}.side-col{position:static}.hero,.section-head,.actions{align-items:stretch;flex-direction:column}.hero .button-secondary{width:100%;text-align:center}.variant-head{align-items:stretch;flex-direction:column}.variant-head .input{max-width:none}}
</style>

<style scoped>
.top-tags{display:flex;align-items:center;gap:8px}.format-pill{font:12px 'DM Mono';color:#3e6381;background:#e8eef5;border-radius:999px;padding:7px 10px}
</style>
